require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'Example' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-document-picker', :path => '../node_modules/react-native-document-picker'

  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  pod 'react-native-pdf', :path => '../node_modules/react-native-pdf'

  pod 'react-native-progress-bar-android', :path => '../node_modules/@react-native-community/progress-bar-android'

  pod 'react-native-progress-view', :path => '../node_modules/@react-native-community/progress-view'

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  pod 'react-native-app-auth', :path => '../node_modules/react-native-app-auth'

  target 'ExampleTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'Example-tvOS' do
  # Pods for Example-tvOS

  target 'Example-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
